---

- name: Run show commands on routers
  hosts: Switches
  gather_facts: no
  vars:
    cli:
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - ios_command:
        commands: sh ip int br
    - ios_command:
        commands: sh ip arp
