---

- name: Run show commands on routers
  hosts: all
  gather_facts: no
  ansible_connection: network_cli
  ansible_network_os: ios
  tasks:
    - ios_command:
        commands: sh ip int br
    - ios_command:
        commands: sh ip arp
